<%@ page pageEncoding="UTF-8"%>
<link rel="shortcut icon" type="image/x-icon" href="http://m.daishumovie.com/copperShare/favicon.ico">
<title>小铜人后台管理系统</title>
<link href="/plugin/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
<link href="/plugin/ligerUI/skins/Gray/css/all.css" rel="stylesheet" type="text/css" />
<link href="/plugin/ligerUI/skins/ligerui-icons.css" rel="stylesheet" type="text/css" />
<link href="/css/common/dc_web.css" rel="stylesheet" type="text/css" />

<link href="/css/common/additional.css" rel="stylesheet" type="text/css" />

<script src="/js/jquery/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-validation/jquery.validate.min.js" type="text/javascript"></script>
<script src="/js/jquery-validation/jquery.metadata.js" type="text/javascript"></script>
<script src="/js/jquery-validation/messages_cn.js" type="text/javascript"></script>
<script src="/js/jquery/jquery.form.min.js" type="text/javascript"></script>
<script src="/plugin/ligerUI/js/ligerui.all.js" type="text/javascript"></script>
<script src="/plugin/ligerUI/js/plugins/ligerTree.js" type="text/javascript"></script>

<script src="/js/common/base.js" type="text/javascript"></script>
<script src="/js/common/map.js" type="text/javascript"></script>
<script src="/js/common/regex.js" type="text/javascript"></script>
<script src="/plugin/picker/WdatePicker.js" type="text/javascript" charset="UTF-8"></script>
